### ISSUE TITLE
Introduce onClick hover/modal

### ISSUE THREAD

**Issue by layik** [tgve/tgvejs#66]
So far TGVE has been relying on `hover`. Having both options will be useful to variety of projects.

**Comment by nbarlowATI** [comment]
So, here's a summary of my understanding of first steps, following the discussion on 16/3/22:
* Create a new component, called "Popup", modelled closely on "Tooltip"
* Make a new function in the "Welcome" component, based on the `_renderTooltip` function, that is called from `onClick` and sets the state variable "popup" (null if the object from onClick is undefined, or the JSX for the Popup component if there is an object).
* Add `{popup}` in Welcome's `render` function (as is done for `tooltip`).
* Think about what css class to use for the popup, to ensure that it appears on top of the map.
* ... (edit this comment as things come to mind)
