### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by LydiaFrance** [tgve/tgvejs#94]
A development workflow for working on `tgvejs` and running it via `app`.

- [x] testing instructions
  - [x] `yarn test` in `tgvejs`
    - [x] Cannot find module 'react' from 'ReactSixteenAdapter.js' -- add to `devDependencies`
- experiments on `master` branch
  - [x] build Docker image
  - [x] `yarn install`/`yarn start`
- experiments on `npm` branch
  - [x] build Docker image :x: `Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'`
  - [x] `yarn install`/`yarn start` :x: `Could not find a required file. Name: index.html`
  - [x] `npm install`/`npm start` :x: [Webpack 4.42.0/4.46.0 dependency issue](https://github.com/facebook/create-react-app/issues/8944)
- <s>resolve #92</s>
- <s>tgve/eatlas-template#4</s> (?)
- [x] identify key users:
  - [x] TGVE contributor
  - <s>Node.js/React developer</s>
  - [x] R developer
  - [x] Python developer (building Flask app)
- <s>native Mac development</s>
  - <s>get to the point where we can run `geoplumber::gp_plumb()` in the R console</s>
- <s>Docker-based development</s>
  - [x] move `Dockerfile` from `eAtlas/npm` to `app` 
  - [x] locally modify `package.json` to point to `file:../eAtlas` ([not `link:`](https://github.com/facebook/react/issues/13824)!)
- [x] identify key use cases
  - [x] contribute to `tgvejs`
  - [x] build custom app based on TGVE?
  - [x] deploy my own copy of TGVE (e.g. locally to work with sensitive data)?
  - [x] use the publicly available deployment of TGVE 
- [x] move change log to separate `.md` file
- [x] #100 
- [x] commit to `yarn` (vs. `npm`) to avoid warnings about `package-lock.json`
- [x] locally modified `package.json` is a bit of a pain
  - [x] `npm link ../tgvejs` seems to achieve same effect but without changing `package.json` 
- dev workflow instructions in `README.md` for `tgvejs` contributors
  - [x] clone `tgvejs` and `app` repos to local machine
  - [x] locally modify `@tgve/tgvejs` dependency in `app/package.json` to point to `link:../tgvejs` 
  - [x] `yarn watch` to incrementally update `dist` dir of `tgvejs`?
    - [x] `app` doesn't pick this up -- need to delete `node_modules/@tgve/**` and then `yarn` again

**Comment by layik** [comment]
Hopefully this becomes much clearer once we deal with #92 and #93.

**Comment by rolyp** [comment]
@layik In the proposed internal dev workflow (where we clone, rather than instantiate, `eatlas-template`), the developer (= me) has to have a locally modified `package.json` and `yarn.lock`. This is not ideal. Any ideas on how we might improve on this?

**Comment by layik** [comment]
OK here is part of the doc I am working on for developers which can replace this Wiki entry. I am happy to refer to how other npm package developers do it but would have to be similar. Here is part of the MD being written.

## Local React App

To develop (make changes) or even better contribute to eAtlas, please set up your own development environment. 

We propose two ways:

* using the eatlas-template OR
* using a clean [CRA](https://reactjs.org/docs/create-a-new-react-app.html) app

There are three steps in either of the two cases:

1. Clone the eAtlas template
2. Transpile it using the provided `package.json` script currently named `dist`. For instance:
 ```sh
 git clone https://github.com/tgve/eAtlas
 cd eAtlas
 npm run dist
 ```
3. Make your dependency of `eatlas` a local one to your step (1)

That should set you up.

### Clean CRA app

### Using eatlas-template

**Comment by layik** [comment]
A Wiki entry like this: https://github.com/tgve/eAtlas/wiki/Developing-eAtlas

**Comment by layik** [comment]
Now, I am happy to say "We propose you create a CRA app from scratch" etc.

**Comment by layik** [comment]
Will do some more tests on using `yarn` and hopefully can commit to yarn as our other repos all use `yarn`. It is a very valid checklist item.

**Comment by layik** [comment]
RE checklist item: "get to the point where we can go `gp_plumb` if this Wiki entry is not fully reproducible, I am happy to make sure it stays fresh. It is one aspect of this work that I like to tell data scientists that our approach is fully reproducible.

https://github.com/tgve/eAtlas/wiki/Reproducible-TGVE

**Comment by layik** [comment]
And perhaps, I need to commit an `.Rmd` that can be run by users and reproduced using an R package like `reprex::reprex()`.

**Comment by rolyp** [comment]
> RE checklist item: "get to the point where we can go `gp_plumb` if this Wiki entry is not fully reproducible, I am happy to make sure it stays fresh. It is one aspect of this work that I like to tell data scientists that our approach is fully reproducible.
> 
> https://github.com/tgve/eAtlas/wiki/Reproducible-TGVE

Won't reproducibiity be exactly what's captured by the Dockerfile? Or do you have something else in mind?

**Comment by rolyp** [comment]
@layik Should we think of the development workflow (assuming a full stack setup that allows change to the R code, React code, etc) as belonging to `full-template`?

**Comment by layik** [comment]
> > RE checklist item: "get to the point where we can go `gp_plumb` if this Wiki entry is not fully reproducible, I am happy to make sure it stays fresh. It is one aspect of this work that I like to tell data scientists that our approach is fully reproducible.
> > https://github.com/tgve/eAtlas/wiki/Reproducible-TGVE
> 
> Won't reproducibiity be exactly what's captured by the Dockerfile? Or do you have something else in mind?

I agree a Dockerfile is a reproducible example. But more like a document in shape of a notebook or an Rmarkdown is what I have in mind for [data] scientists.

**Comment by layik** [comment]
> @layik Should we think of the development workflow (assuming a full stack setup that allows change to the R code, React code, etc) as belonging to `full-template`?

For me this is what we discussed today and a "development workflow" would be what a developer would be doing to develop eAtlas npm package.

**Comment by rolyp** [comment]
@layik Ok. Perhaps this could build on what's currently in the `jupyter` repo?

**Comment by layik** [comment]
You mean the full-template sticking with R to make my life easier.

**Comment by rolyp** [comment]
Let's talk about this tomorrow morning.
