### ISSUE TITLE
Rename eAtlas

### ISSUE THREAD

**Issue by layik** [tgve/tgvejs#97]
- [x] `eAtlas` -> `tgvejs`
- [x] `eatlas-template` -> `app`
- [x] `full-template` -> `app-full`
- [x] use notation `tgve/app`, `tgve/full-app` in docs
- <s>revisit `tgve-` prefix for `app`, `app-full`</s>
- [x] search and replace all occurrences of `eAtlas`
- [x] rename `main`/`master` branches in `app` and `spenser` to `release`
- [x] references to `eatlas-data`
- [x] `wip.R` refers to `~/Desktop/recent/eAtlas` (2+ years old, delete?)
- [x] `package.json` in `full-app` identifies package as `eatlas-template`
- [x] `package.json` in `spenser` identifies package as `eatlas`
- [x] rename `eatlas-data`
- [x] `tgve.R` refers to `eatlas-template`
- [x] rename `npm` component
- [x] `gh-pages.yml` in `app` and `full-app` refers to `layik`
- [x] https://badge.fury.io/js/eatlas.svg 
- [x] `get_quant.R`, `get_spenser.R`, `plumber.R` and `Header.jsx` in `spenser` refer to `layik/eAtlas`
- [x] `rollup.config.js` in `tgvejs` refers to (generates?) `dist/eatlas.js`
- [x] update links to npm package

**Comment by rolyp** [comment]
@layik I think I see the case now for renaming the `eAtlas` repo.

**Comment by layik** [comment]
Once we commit fully to the name TGVE, I propose `tgvejs`.

**Comment by rolyp** [comment]
@layik See top of issue for current proposal.

**Comment by layik** [comment]
Thank you @rolyp. One more suggestion to make it even more difficult:
-  `eAtlas` -> `tgvejs`
-  `eatlas-template` -> `app`
-  `full-template` -> `app-full`?

As we have `/tgve` from the org name anyways.

**Comment by rolyp** [comment]
@layik I like your suggestion better -- updated the proposal at the top.

**Comment by layik** [comment]
In relation to first checkbox (renaming eAtlas -> tgvejs), this is where I have been hung/stuck:

https://stackoverflow.com/a/28841779/11101153

**Comment by layik** [comment]
RE third item (rename `full-template` -> `full-app`), there is the feeling that the repo name still does not reflect it fully. So had to use `tgve-full-app` in the repo's README. In fact that is what I should be doing for the second one as well :(

**Comment by layik** [comment]
In short, the logic (which I proposed) of relying on GH organisational naming `tgve/app` does not automatically reflect onto README/docs/papers/presentations.

**Comment by rolyp** [comment]
> In relation to first checkbox (renaming eAtlas -> tgvejs), this is where I have been hung/stuck:
> 
> https://stackoverflow.com/a/28841779/11101153

Perhaps we can just deprecate the old component and release a new one with the new name.

**Comment by rolyp** [comment]
@layik I guess we should either:
- revert to `tgve-app` and `tgve-full-app` as originally proposed, or
- refer to them as `tgve/app` and `tgve/full-app` in docs etc

(The latter is consistent with the GitHub convention for referring to issues in other repos.)

**Comment by layik** [comment]
Thanks @rolyp. Please let me know your preference of the two.

**Comment by rolyp** [comment]
@layik I feel like we're good to delete

> `            sed -i "s/layik/${a[0]}/" package.json`

from `gh-pages.yml` (in `app` and `full-app`), since there are no longer any references to `layik` in the baseline `package.json`.

(Btw: how are ${a[0]} and ${a[1]} resolved?)

**Comment by rolyp** [comment]
@layik Unless you tell me otherwise planning to rename `eatlas-data` to `example-data` or similar.

**Comment by layik** [comment]
> @layik I feel like we're good to delete
> 
> > `            sed -i "s/layik/${a[0]}/" package.json`
> 
> from `gh-pages.yml` (in `app` and `full-app`), since there are no longer any references to `layik` in the baseline `package.json`.
> 
> (Btw: how are ${a[0]} and ${a[1]} resolved?)

Sorry @rolyp for late response to this. I think you edited the file(s) but this is important for people who "fork the template". So `app` and `full-app` would need to be replaced with their repository names.
